services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=rethink_db
      - PORT=8000
      - DB_SYNC=true
    volumes:
      - ./backend:/app
      - /app/node_modules
      # TODO: use monorepo structure with shared functions and types, not doing this now
      #    because there is another big PR open for flows V2 which will cause a lot of conflicts now...
      # - ../types:/app/types

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rethink_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
