/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { Permissions } from "./Permissions";
export type { Roles } from "./Roles";
