/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  Addressable,
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RolesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowTarget"
      | "assignRoles"
      | "avatar"
      | "defaultRoles"
      | "disableModule"
      | "enableModule"
      | "execTransactionFromModule"
      | "execTransactionFromModuleReturnData"
      | "execTransactionWithRole"
      | "execTransactionWithRoleReturnData"
      | "getGuard"
      | "getModulesPaginated"
      | "guard"
      | "isModuleEnabled"
      | "multisend"
      | "owner"
      | "renounceOwnership"
      | "revokeTarget"
      | "scopeAllowFunction"
      | "scopeFunction"
      | "scopeFunctionExecutionOptions"
      | "scopeParameter"
      | "scopeParameterAsOneOf"
      | "scopeRevokeFunction"
      | "scopeTarget"
      | "setAvatar"
      | "setDefaultRole"
      | "setGuard"
      | "setMultisend"
      | "setTarget"
      | "setUp"
      | "target"
      | "transferOwnership"
      | "unscopeParameter"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssignRoles"
      | "AvatarSet"
      | "ChangedGuard"
      | "DisabledModule"
      | "EnabledModule"
      | "OwnershipTransferred"
      | "RolesModSetup"
      | "SetDefaultRole"
      | "SetMultisendAddress"
      | "TargetSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowTarget",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignRoles",
    values: [AddressLike, BigNumberish[], boolean[]]
  ): string;
  encodeFunctionData(functionFragment: "avatar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "defaultRoles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disableModule",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enableModule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execTransactionFromModule",
    values: [AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "execTransactionFromModuleReturnData",
    values: [AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "execTransactionWithRole",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "execTransactionWithRoleReturnData",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(functionFragment: "getGuard", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getModulesPaginated",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "guard", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isModuleEnabled",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "multisend", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTarget",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeAllowFunction",
    values: [BigNumberish, AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeFunction",
    values: [
      BigNumberish,
      AddressLike,
      BytesLike,
      boolean[],
      BigNumberish[],
      BigNumberish[],
      BytesLike[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeFunctionExecutionOptions",
    values: [BigNumberish, AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeParameter",
    values: [
      BigNumberish,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeParameterAsOneOf",
    values: [
      BigNumberish,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeRevokeFunction",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeTarget",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAvatar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGuard",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMultisend",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTarget",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setUp", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "target", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unscopeParameter",
    values: [BigNumberish, AddressLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "avatar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execTransactionFromModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execTransactionFromModuleReturnData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execTransactionWithRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execTransactionWithRoleReturnData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGuard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getModulesPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isModuleEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multisend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeAllowFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeFunctionExecutionOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeParameter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeParameterAsOneOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeRevokeFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAvatar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGuard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMultisend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setTarget", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "target", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unscopeParameter",
    data: BytesLike
  ): Result;
}

export namespace AssignRolesEvent {
  export type InputTuple = [
    module: AddressLike,
    roles: BigNumberish[],
    memberOf: boolean[]
  ];
  export type OutputTuple = [
    module: string,
    roles: bigint[],
    memberOf: boolean[]
  ];
  export interface OutputObject {
    module: string;
    roles: bigint[];
    memberOf: boolean[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AvatarSetEvent {
  export type InputTuple = [
    previousAvatar: AddressLike,
    newAvatar: AddressLike
  ];
  export type OutputTuple = [previousAvatar: string, newAvatar: string];
  export interface OutputObject {
    previousAvatar: string;
    newAvatar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChangedGuardEvent {
  export type InputTuple = [guard: AddressLike];
  export type OutputTuple = [guard: string];
  export interface OutputObject {
    guard: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisabledModuleEvent {
  export type InputTuple = [module: AddressLike];
  export type OutputTuple = [module: string];
  export interface OutputObject {
    module: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EnabledModuleEvent {
  export type InputTuple = [module: AddressLike];
  export type OutputTuple = [module: string];
  export interface OutputObject {
    module: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RolesModSetupEvent {
  export type InputTuple = [
    initiator: AddressLike,
    owner: AddressLike,
    avatar: AddressLike,
    target: AddressLike
  ];
  export type OutputTuple = [
    initiator: string,
    owner: string,
    avatar: string,
    target: string
  ];
  export interface OutputObject {
    initiator: string;
    owner: string;
    avatar: string;
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetDefaultRoleEvent {
  export type InputTuple = [module: AddressLike, defaultRole: BigNumberish];
  export type OutputTuple = [module: string, defaultRole: bigint];
  export interface OutputObject {
    module: string;
    defaultRole: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetMultisendAddressEvent {
  export type InputTuple = [multisendAddress: AddressLike];
  export type OutputTuple = [multisendAddress: string];
  export interface OutputObject {
    multisendAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetSetEvent {
  export type InputTuple = [
    previousTarget: AddressLike,
    newTarget: AddressLike
  ];
  export type OutputTuple = [previousTarget: string, newTarget: string];
  export interface OutputObject {
    previousTarget: string;
    newTarget: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Roles extends BaseContract {
  connect(runner?: ContractRunner | null): Roles;
  attach(target: string | Addressable): Roles;
  waitForDeployment(): Promise<this>;

  interface: RolesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowTarget: TypedContractMethod<
    [role: BigNumberish, targetAddress: AddressLike, options: BigNumberish],
    [void],
    "nonpayable"
  >;

  assignRoles: TypedContractMethod<
    [module: AddressLike, _roles: BigNumberish[], memberOf: boolean[]],
    [void],
    "nonpayable"
  >;

  avatar: TypedContractMethod<[], [string], "view">;

  defaultRoles: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  disableModule: TypedContractMethod<
    [prevModule: AddressLike, module: AddressLike],
    [void],
    "nonpayable"
  >;

  enableModule: TypedContractMethod<
    [module: AddressLike],
    [void],
    "nonpayable"
  >;

  execTransactionFromModule: TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  execTransactionFromModuleReturnData: TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish
    ],
    [[boolean, string]],
    "nonpayable"
  >;

  execTransactionWithRole: TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean
    ],
    [boolean],
    "nonpayable"
  >;

  execTransactionWithRoleReturnData: TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean
    ],
    [[boolean, string] & { success: boolean; returnData: string }],
    "nonpayable"
  >;

  getGuard: TypedContractMethod<[], [string], "view">;

  getModulesPaginated: TypedContractMethod<
    [start: AddressLike, pageSize: BigNumberish],
    [[string[], string] & { array: string[]; next: string }],
    "view"
  >;

  guard: TypedContractMethod<[], [string], "view">;

  isModuleEnabled: TypedContractMethod<
    [_module: AddressLike],
    [boolean],
    "view"
  >;

  multisend: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeTarget: TypedContractMethod<
    [role: BigNumberish, targetAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  scopeAllowFunction: TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      options: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  scopeFunction: TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      isParamScoped: boolean[],
      paramType: BigNumberish[],
      paramComp: BigNumberish[],
      compValue: BytesLike[],
      options: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  scopeFunctionExecutionOptions: TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      options: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  scopeParameter: TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      paramComp: BigNumberish,
      compValue: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  scopeParameterAsOneOf: TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      compValues: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  scopeRevokeFunction: TypedContractMethod<
    [role: BigNumberish, targetAddress: AddressLike, functionSig: BytesLike],
    [void],
    "nonpayable"
  >;

  scopeTarget: TypedContractMethod<
    [role: BigNumberish, targetAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setAvatar: TypedContractMethod<[_avatar: AddressLike], [void], "nonpayable">;

  setDefaultRole: TypedContractMethod<
    [module: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGuard: TypedContractMethod<[_guard: AddressLike], [void], "nonpayable">;

  setMultisend: TypedContractMethod<
    [_multisend: AddressLike],
    [void],
    "nonpayable"
  >;

  setTarget: TypedContractMethod<[_target: AddressLike], [void], "nonpayable">;

  setUp: TypedContractMethod<[initParams: BytesLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unscopeParameter: TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      paramIndex: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowTarget"
  ): TypedContractMethod<
    [role: BigNumberish, targetAddress: AddressLike, options: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignRoles"
  ): TypedContractMethod<
    [module: AddressLike, _roles: BigNumberish[], memberOf: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "avatar"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultRoles"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "disableModule"
  ): TypedContractMethod<
    [prevModule: AddressLike, module: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enableModule"
  ): TypedContractMethod<[module: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "execTransactionFromModule"
  ): TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "execTransactionFromModuleReturnData"
  ): TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish
    ],
    [[boolean, string]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "execTransactionWithRole"
  ): TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "execTransactionWithRoleReturnData"
  ): TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean
    ],
    [[boolean, string] & { success: boolean; returnData: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGuard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getModulesPaginated"
  ): TypedContractMethod<
    [start: AddressLike, pageSize: BigNumberish],
    [[string[], string] & { array: string[]; next: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "guard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isModuleEnabled"
  ): TypedContractMethod<[_module: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "multisend"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeTarget"
  ): TypedContractMethod<
    [role: BigNumberish, targetAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scopeAllowFunction"
  ): TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      options: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scopeFunction"
  ): TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      isParamScoped: boolean[],
      paramType: BigNumberish[],
      paramComp: BigNumberish[],
      compValue: BytesLike[],
      options: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scopeFunctionExecutionOptions"
  ): TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      options: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scopeParameter"
  ): TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      paramComp: BigNumberish,
      compValue: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scopeParameterAsOneOf"
  ): TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      compValues: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scopeRevokeFunction"
  ): TypedContractMethod<
    [role: BigNumberish, targetAddress: AddressLike, functionSig: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scopeTarget"
  ): TypedContractMethod<
    [role: BigNumberish, targetAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAvatar"
  ): TypedContractMethod<[_avatar: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultRole"
  ): TypedContractMethod<
    [module: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGuard"
  ): TypedContractMethod<[_guard: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMultisend"
  ): TypedContractMethod<[_multisend: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTarget"
  ): TypedContractMethod<[_target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUp"
  ): TypedContractMethod<[initParams: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "target"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unscopeParameter"
  ): TypedContractMethod<
    [
      role: BigNumberish,
      targetAddress: AddressLike,
      functionSig: BytesLike,
      paramIndex: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AssignRoles"
  ): TypedContractEvent<
    AssignRolesEvent.InputTuple,
    AssignRolesEvent.OutputTuple,
    AssignRolesEvent.OutputObject
  >;
  getEvent(
    key: "AvatarSet"
  ): TypedContractEvent<
    AvatarSetEvent.InputTuple,
    AvatarSetEvent.OutputTuple,
    AvatarSetEvent.OutputObject
  >;
  getEvent(
    key: "ChangedGuard"
  ): TypedContractEvent<
    ChangedGuardEvent.InputTuple,
    ChangedGuardEvent.OutputTuple,
    ChangedGuardEvent.OutputObject
  >;
  getEvent(
    key: "DisabledModule"
  ): TypedContractEvent<
    DisabledModuleEvent.InputTuple,
    DisabledModuleEvent.OutputTuple,
    DisabledModuleEvent.OutputObject
  >;
  getEvent(
    key: "EnabledModule"
  ): TypedContractEvent<
    EnabledModuleEvent.InputTuple,
    EnabledModuleEvent.OutputTuple,
    EnabledModuleEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RolesModSetup"
  ): TypedContractEvent<
    RolesModSetupEvent.InputTuple,
    RolesModSetupEvent.OutputTuple,
    RolesModSetupEvent.OutputObject
  >;
  getEvent(
    key: "SetDefaultRole"
  ): TypedContractEvent<
    SetDefaultRoleEvent.InputTuple,
    SetDefaultRoleEvent.OutputTuple,
    SetDefaultRoleEvent.OutputObject
  >;
  getEvent(
    key: "SetMultisendAddress"
  ): TypedContractEvent<
    SetMultisendAddressEvent.InputTuple,
    SetMultisendAddressEvent.OutputTuple,
    SetMultisendAddressEvent.OutputObject
  >;
  getEvent(
    key: "TargetSet"
  ): TypedContractEvent<
    TargetSetEvent.InputTuple,
    TargetSetEvent.OutputTuple,
    TargetSetEvent.OutputObject
  >;

  filters: {
    "AssignRoles(address,uint16[],bool[])": TypedContractEvent<
      AssignRolesEvent.InputTuple,
      AssignRolesEvent.OutputTuple,
      AssignRolesEvent.OutputObject
    >;
    AssignRoles: TypedContractEvent<
      AssignRolesEvent.InputTuple,
      AssignRolesEvent.OutputTuple,
      AssignRolesEvent.OutputObject
    >;

    "AvatarSet(address,address)": TypedContractEvent<
      AvatarSetEvent.InputTuple,
      AvatarSetEvent.OutputTuple,
      AvatarSetEvent.OutputObject
    >;
    AvatarSet: TypedContractEvent<
      AvatarSetEvent.InputTuple,
      AvatarSetEvent.OutputTuple,
      AvatarSetEvent.OutputObject
    >;

    "ChangedGuard(address)": TypedContractEvent<
      ChangedGuardEvent.InputTuple,
      ChangedGuardEvent.OutputTuple,
      ChangedGuardEvent.OutputObject
    >;
    ChangedGuard: TypedContractEvent<
      ChangedGuardEvent.InputTuple,
      ChangedGuardEvent.OutputTuple,
      ChangedGuardEvent.OutputObject
    >;

    "DisabledModule(address)": TypedContractEvent<
      DisabledModuleEvent.InputTuple,
      DisabledModuleEvent.OutputTuple,
      DisabledModuleEvent.OutputObject
    >;
    DisabledModule: TypedContractEvent<
      DisabledModuleEvent.InputTuple,
      DisabledModuleEvent.OutputTuple,
      DisabledModuleEvent.OutputObject
    >;

    "EnabledModule(address)": TypedContractEvent<
      EnabledModuleEvent.InputTuple,
      EnabledModuleEvent.OutputTuple,
      EnabledModuleEvent.OutputObject
    >;
    EnabledModule: TypedContractEvent<
      EnabledModuleEvent.InputTuple,
      EnabledModuleEvent.OutputTuple,
      EnabledModuleEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RolesModSetup(address,address,address,address)": TypedContractEvent<
      RolesModSetupEvent.InputTuple,
      RolesModSetupEvent.OutputTuple,
      RolesModSetupEvent.OutputObject
    >;
    RolesModSetup: TypedContractEvent<
      RolesModSetupEvent.InputTuple,
      RolesModSetupEvent.OutputTuple,
      RolesModSetupEvent.OutputObject
    >;

    "SetDefaultRole(address,uint16)": TypedContractEvent<
      SetDefaultRoleEvent.InputTuple,
      SetDefaultRoleEvent.OutputTuple,
      SetDefaultRoleEvent.OutputObject
    >;
    SetDefaultRole: TypedContractEvent<
      SetDefaultRoleEvent.InputTuple,
      SetDefaultRoleEvent.OutputTuple,
      SetDefaultRoleEvent.OutputObject
    >;

    "SetMultisendAddress(address)": TypedContractEvent<
      SetMultisendAddressEvent.InputTuple,
      SetMultisendAddressEvent.OutputTuple,
      SetMultisendAddressEvent.OutputObject
    >;
    SetMultisendAddress: TypedContractEvent<
      SetMultisendAddressEvent.InputTuple,
      SetMultisendAddressEvent.OutputTuple,
      SetMultisendAddressEvent.OutputObject
    >;

    "TargetSet(address,address)": TypedContractEvent<
      TargetSetEvent.InputTuple,
      TargetSetEvent.OutputTuple,
      TargetSetEvent.OutputObject
    >;
    TargetSet: TypedContractEvent<
      TargetSetEvent.InputTuple,
      TargetSetEvent.OutputTuple,
      TargetSetEvent.OutputObject
    >;
  };
}
