/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Mock } from "./Mock";
export type { MultiSend } from "./MultiSend";
export type { TestAvatar } from "./TestAvatar";
export type { TestContract } from "./TestContract";
export type { TestPluckParam } from "./TestPluckParam";
