import { it, expect, describe } from "vitest"
import { FunctionFragment } from "ethers";
import { flattenAbiFunctionInputs } from "~/composables/zodiac-roles/flattenAbiFunctionInputs";

describe("flattenAbiFunctionInputs", () => {
  it("flatten nested tuples- (depth: 3)", () => {
    expect(flattenAbiFunctionInputs(mockFunc?.inputs)).toEqual(mockResult);
  });
  it("flatten array with nested tuples", () => {
    expect(flattenAbiFunctionInputs(mockFunc3?.inputs)).toEqual(mockResult3);
  });
});

const mockFunc = FunctionFragment.from({
  "type": "function",
  "inputs":
    [
      {
        "name": "executor",
        "type": "address",
        "baseType": "address",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "desc",
        "type": "tuple",
        "baseType": "tuple",
        "components":
          [
            {
              "name": "srcToken",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "dstToken",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "srcReceiver",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "dstReceiver",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "amount",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "minReturnAmount",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "flags",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "extraParams",
              "type": "tuple",
              "baseType": "tuple",
              "components":
                [
                  {
                    "name": "param1",
                    "type": "string",
                    "baseType": "string",
                    "components": null,
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                  {
                    "name": "param2",
                    "type": "string",
                    "baseType": "string",
                    "components": null,
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                ],
              "arrayLength": null,
              "arrayChildren": null,
            },
          ],
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "data",
        "type": "bytes",
        "baseType": "bytes",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
    ],
  "name": "swap",
  "constant": false,
  "outputs":
    [
      {
        "name": "returnAmount",
        "type": "uint256",
        "baseType": "uint256",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "spentAmount",
        "type": "uint256",
        "baseType": "uint256",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
    ],
  "stateMutability": "payable",
  "payable": true,
  "gas": null,
}) as FunctionFragment;

const mockResult = [
  {
    "name": "executor",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 0,
    "parentIndex": null,
    "parentName": "",
  },
  {
    "name": "srcToken",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 1,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "dstToken",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 2,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "srcReceiver",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 3,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "dstReceiver",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 4,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "amount",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 5,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "minReturnAmount",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 6,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "flags",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 7,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "param1",
    "type": "string",
    "baseType": "string",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 8,
    "parentIndex": 8,
    "parentName": "desc extraParams",
  },
  {
    "name": "param2",
    "type": "string",
    "baseType": "string",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 9,
    "parentIndex": 8,
    "parentName": "desc extraParams",
  },
  {
    "name": "data",
    "type": "bytes",
    "baseType": "bytes",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 10,
    "parentIndex": null,
    "parentName": "",
  },
];


const mockFunc2 = FunctionFragment.from({
  "type": "function",
  "inputs":
    [
      {
        "name": "executor",
        "type": "address",
        "baseType": "address",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "desc",
        "type": "tuple",
        "baseType": "tuple",
        "components":
          [
            {
              "name": "srcToken",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "dstToken",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "srcReceiver",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "dstReceiver",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "amount",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "minReturnAmount",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "flags",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "extraParams",
              "type": "tuple",
              "baseType": "tuple",
              "components":
                [
                  {
                    "name": "param1",
                    "type": "string",
                    "baseType": "string",
                    "components": null,
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                  {
                    "name": "param2",
                    "type": "string",
                    "baseType": "string",
                    "components": null,
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                  {
                    "name": "param3",
                    "type": "tuple",
                    "baseType": "tuple",
                    "components": [
                      {
                        "name": "param3_1",
                        "type": "string",
                        "baseType": "string",
                        "components": null,
                        "arrayLength": null,
                        "arrayChildren": null,
                      },
                      {
                        "name": "param3_2",
                        "type": "string",
                        "baseType": "string",
                        "components": null,
                        "arrayLength": null,
                        "arrayChildren": null,
                      },
                    ],
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                  {
                    "name": "param4",
                    "type": "string",
                    "baseType": "string",
                    "components": null,
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                ],
              "arrayLength": null,
              "arrayChildren": null,
            },
          ],
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "data",
        "type": "bytes",
        "baseType": "bytes",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
    ],
  "name": "swap",
  "constant": false,
  "outputs":
    [
      {
        "name": "returnAmount",
        "type": "uint256",
        "baseType": "uint256",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "spentAmount",
        "type": "uint256",
        "baseType": "uint256",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
    ],
  "stateMutability": "payable",
  "payable": true,
  "gas": null,
}) as FunctionFragment;

const mockFunc3 = FunctionFragment.from({
  "inputs": [
    {
      "components": [
        {
          "internalType": "enum IGovernableFundStorage.NavUpdateType",
          "name": "entryType",
          "type": "uint8",
        },
        {
          "components": [
            {
              "internalType": "address",
              "name": "tokenPair",
              "type": "address",
            },
            {
              "internalType": "address",
              "name": "aggregatorAddress",
              "type": "address",
            },
            {
              "internalType": "bytes",
              "name": "functionSignatureWithEncodedInputs",
              "type": "bytes",
            },
            {
              "internalType": "address",
              "name": "assetTokenAddress",
              "type": "address",
            },
            {
              "internalType": "address",
              "name": "nonAssetTokenAddress",
              "type": "address",
            },
            {
              "internalType": "bool",
              "name": "isReturnArray",
              "type": "bool",
            },
            {
              "internalType": "uint256",
              "name": "returnLength",
              "type": "uint256",
            },
            {
              "internalType": "uint256",
              "name": "returnIndex",
              "type": "uint256",
            },
            {
              "internalType": "uint256",
              "name": "pastNAVUpdateIndex",
              "type": "uint256",
            },
          ],
          "internalType": "struct IGovernableFundStorage.NAVLiquidUpdate[]",
          "name": "liquid",
          "type": "tuple[]",
        },
        {
          "components": [
            {
              "internalType": "uint256",
              "name": "baseCurrencySpent",
              "type": "uint256",
            },
            {
              "internalType": "uint256",
              "name": "amountAquiredTokens",
              "type": "uint256",
            },
            {
              "internalType": "address",
              "name": "tokenAddress",
              "type": "address",
            },
            {
              "internalType": "bool",
              "name": "isNFT",
              "type": "bool",
            },
            {
              "internalType": "string[]",
              "name": "otcTxHashes",
              "type": "string[]",
            },
            {
              "internalType": "enum IGovernableFundStorage.NAVNFTType",
              "name": "nftType",
              "type": "uint8",
            },
            {
              "internalType": "uint256",
              "name": "nftIndex",
              "type": "uint256",
            },
            {
              "internalType": "uint256",
              "name": "pastNAVUpdateIndex",
              "type": "uint256",
            },
          ],
          "internalType": "struct IGovernableFundStorage.NAVIlliquidUpdate[]",
          "name": "illiquid",
          "type": "tuple[]",
        },
        {
          "components": [
            {
              "internalType": "address",
              "name": "oracleAddress",
              "type": "address",
            },
            {
              "internalType": "address",
              "name": "nftAddress",
              "type": "address",
            },
            {
              "internalType": "enum IGovernableFundStorage.NAVNFTType",
              "name": "nftType",
              "type": "uint8",
            },
            {
              "internalType": "uint256",
              "name": "nftIndex",
              "type": "uint256",
            },
            {
              "internalType": "uint256",
              "name": "pastNAVUpdateIndex",
              "type": "uint256",
            },
          ],
          "internalType": "struct IGovernableFundStorage.NAVNFTUpdate[]",
          "name": "nft",
          "type": "tuple[]",
        },
        {
          "components": [
            {
              "internalType": "address",
              "name": "remoteContractAddress",
              "type": "address",
            },
            {
              "internalType": "string",
              "name": "functionSignatures",
              "type": "string",
            },
            {
              "internalType": "bytes",
              "name": "encodedFunctionSignatureWithInputs",
              "type": "bytes",
            },
            {
              "internalType": "uint256",
              "name": "normalizationDecimals",
              "type": "uint256",
            },
            {
              "internalType": "bool",
              "name": "isReturnArray",
              "type": "bool",
            },
            {
              "internalType": "uint256",
              "name": "returnValIndex",
              "type": "uint256",
            },
            {
              "internalType": "uint256",
              "name": "returnArraySize",
              "type": "uint256",
            },
            {
              "internalType": "enum IGovernableFundStorage.NAVComposableUpdateReturnType",
              "name": "returnValType",
              "type": "uint8",
            },
            {
              "internalType": "uint256",
              "name": "pastNAVUpdateIndex",
              "type": "uint256",
            },
            {
              "internalType": "bool",
              "name": "isNegative",
              "type": "bool",
            },
          ],
          "internalType": "struct IGovernableFundStorage.NAVComposableUpdate[]",
          "name": "composable",
          "type": "tuple[]",
        },
        {
          "internalType": "bool",
          "name": "isPastNAVUpdate",
          "type": "bool",
        },
        {
          "internalType": "uint256",
          "name": "pastNAVUpdateIndex",
          "type": "uint256",
        },
        {
          "internalType": "uint256",
          "name": "pastNAVUpdateEntryIndex",
          "type": "uint256",
        },
        {
          "internalType": "string",
          "name": "description",
          "type": "string",
        },
      ],
      "internalType": "struct IGovernableFundStorage.NavUpdateEntry[]",
      "name": "navUpdateData",
      "type": "tuple[]",
    },
    {
      "internalType": "address[]",
      "name": "pastNAVUpdateEntryFundAddress",
      "type": "address[]",
    },
    {
      "internalType": "bool",
      "name": "processWithdraw",
      "type": "bool",
    },
  ],
  "name": "updateNav",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}) as FunctionFragment;


const mockResult3 = [
  {
    "name": "entryType",
    "type": "uint8",
    "baseType": "uint8",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 0,
    "parentIndex": 0,
    "parentName": "navUpdateData ",
  },
  {
    "name": "tokenPair",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 1,
    "parentIndex": 1,
    "parentName": "navUpdateData  liquid ",
  },
  {
    "name": "aggregatorAddress",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 2,
    "parentIndex": 1,
    "parentName": "navUpdateData  liquid ",
  },
  {
    "name": "functionSignatureWithEncodedInputs",
    "type": "bytes",
    "baseType": "bytes",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 3,
    "parentIndex": 1,
    "parentName": "navUpdateData  liquid ",
  },
  {
    "name": "assetTokenAddress",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 4,
    "parentIndex": 1,
    "parentName": "navUpdateData  liquid ",
  },
  {
    "name": "nonAssetTokenAddress",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 5,
    "parentIndex": 1,
    "parentName": "navUpdateData  liquid ",
  },
  {
    "name": "isReturnArray",
    "type": "bool",
    "baseType": "bool",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 6,
    "parentIndex": 1,
    "parentName": "navUpdateData  liquid ",
  },
  {
    "name": "returnLength",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 7,
    "parentIndex": 1,
    "parentName": "navUpdateData  liquid ",
  },
  {
    "name": "returnIndex",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 8,
    "parentIndex": 1,
    "parentName": "navUpdateData  liquid ",
  },
  {
    "name": "pastNAVUpdateIndex",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 9,
    "parentIndex": 1,
    "parentName": "navUpdateData  liquid ",
  },
  {
    "name": "baseCurrencySpent",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 10,
    "parentIndex": 10,
    "parentName": "navUpdateData  illiquid ",
  },
  {
    "name": "amountAquiredTokens",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 11,
    "parentIndex": 10,
    "parentName": "navUpdateData  illiquid ",
  },
  {
    "name": "tokenAddress",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 12,
    "parentIndex": 10,
    "parentName": "navUpdateData  illiquid ",
  },
  {
    "name": "isNFT",
    "type": "bool",
    "baseType": "bool",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 13,
    "parentIndex": 10,
    "parentName": "navUpdateData  illiquid ",
  },
  {
    "name": "",
    "type": "string",
    "baseType": "string",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 14,
    "parentIndex": 14,
    "parentName": "navUpdateData  illiquid  otcTxHashes",
  },
  {
    "name": "nftType",
    "type": "uint8",
    "baseType": "uint8",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 15,
    "parentIndex": 10,
    "parentName": "navUpdateData  illiquid ",
  },
  {
    "name": "nftIndex",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 16,
    "parentIndex": 10,
    "parentName": "navUpdateData  illiquid ",
  },
  {
    "name": "pastNAVUpdateIndex",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 17,
    "parentIndex": 10,
    "parentName": "navUpdateData  illiquid ",
  },
  {
    "name": "oracleAddress",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 18,
    "parentIndex": 18,
    "parentName": "navUpdateData  nft ",
  },
  {
    "name": "nftAddress",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 19,
    "parentIndex": 18,
    "parentName": "navUpdateData  nft ",
  },
  {
    "name": "nftType",
    "type": "uint8",
    "baseType": "uint8",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 20,
    "parentIndex": 18,
    "parentName": "navUpdateData  nft ",
  },
  {
    "name": "nftIndex",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 21,
    "parentIndex": 18,
    "parentName": "navUpdateData  nft ",
  },
  {
    "name": "pastNAVUpdateIndex",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 22,
    "parentIndex": 18,
    "parentName": "navUpdateData  nft ",
  },
  {
    "name": "remoteContractAddress",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 23,
    "parentIndex": 23,
    "parentName": "navUpdateData  composable ",
  },
  {
    "name": "functionSignatures",
    "type": "string",
    "baseType": "string",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 24,
    "parentIndex": 23,
    "parentName": "navUpdateData  composable ",
  },
  {
    "name": "encodedFunctionSignatureWithInputs",
    "type": "bytes",
    "baseType": "bytes",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 25,
    "parentIndex": 23,
    "parentName": "navUpdateData  composable ",
  },
  {
    "name": "normalizationDecimals",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 26,
    "parentIndex": 23,
    "parentName": "navUpdateData  composable ",
  },
  {
    "name": "isReturnArray",
    "type": "bool",
    "baseType": "bool",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 27,
    "parentIndex": 23,
    "parentName": "navUpdateData  composable ",
  },
  {
    "name": "returnValIndex",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 28,
    "parentIndex": 23,
    "parentName": "navUpdateData  composable ",
  },
  {
    "name": "returnArraySize",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 29,
    "parentIndex": 23,
    "parentName": "navUpdateData  composable ",
  },
  {
    "name": "returnValType",
    "type": "uint8",
    "baseType": "uint8",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 30,
    "parentIndex": 23,
    "parentName": "navUpdateData  composable ",
  },
  {
    "name": "pastNAVUpdateIndex",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 31,
    "parentIndex": 23,
    "parentName": "navUpdateData  composable ",
  },
  {
    "name": "isNegative",
    "type": "bool",
    "baseType": "bool",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 32,
    "parentIndex": 23,
    "parentName": "navUpdateData  composable ",
  },
  {
    "name": "isPastNAVUpdate",
    "type": "bool",
    "baseType": "bool",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 33,
    "parentIndex": 0,
    "parentName": "navUpdateData ",
  },
  {
    "name": "pastNAVUpdateIndex",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 34,
    "parentIndex": 0,
    "parentName": "navUpdateData ",
  },
  {
    "name": "pastNAVUpdateEntryIndex",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 35,
    "parentIndex": 0,
    "parentName": "navUpdateData ",
  },
  {
    "name": "description",
    "type": "string",
    "baseType": "string",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 36,
    "parentIndex": 0,
    "parentName": "navUpdateData ",
  },
  {
    "name": "",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 37,
    "parentIndex": 37,
    "parentName": "pastNAVUpdateEntryFundAddress",
  },
  {
    "name": "processWithdraw",
    "type": "bool",
    "baseType": "bool",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 38,
    "parentIndex": null,
    "parentName": "",
  },
];
