import { it, expect, describe } from "vitest"
import { FunctionFragment } from "ethers";
import { flattenAbiFunctionInputs } from "~/composables/zodiac-roles/flattenAbiFunctionInputs";

describe("flattenAbiFunctionInputs", () => {
  it("flatten nested tuples- (depth: 3)", () => {
    expect(flattenAbiFunctionInputs(mockFunc?.inputs)).toEqual(mockResult);
  });
});

const mockFunc = FunctionFragment.from({
  "type": "function",
  "inputs":
    [
      {
        "name": "executor",
        "type": "address",
        "baseType": "address",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "desc",
        "type": "tuple",
        "baseType": "tuple",
        "components":
          [
            {
              "name": "srcToken",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "dstToken",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "srcReceiver",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "dstReceiver",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "amount",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "minReturnAmount",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "flags",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "extraParams",
              "type": "tuple",
              "baseType": "tuple",
              "components":
                [
                  {
                    "name": "param1",
                    "type": "string",
                    "baseType": "string",
                    "components": null,
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                  {
                    "name": "param2",
                    "type": "string",
                    "baseType": "string",
                    "components": null,
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                ],
              "arrayLength": null,
              "arrayChildren": null,
            },
          ],
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "data",
        "type": "bytes",
        "baseType": "bytes",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
    ],
  "name": "swap",
  "constant": false,
  "outputs":
    [
      {
        "name": "returnAmount",
        "type": "uint256",
        "baseType": "uint256",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "spentAmount",
        "type": "uint256",
        "baseType": "uint256",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
    ],
  "stateMutability": "payable",
  "payable": true,
  "gas": null,
}) as FunctionFragment;

const mockResult = [
  {
    "name": "executor",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 0,
    "parentIndex": null,
    "parentName": "",
  },
  {
    "name": "srcToken",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 1,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "dstToken",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 2,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "srcReceiver",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 3,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "dstReceiver",
    "type": "address",
    "baseType": "address",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 4,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "amount",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 5,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "minReturnAmount",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 6,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "flags",
    "type": "uint256",
    "baseType": "uint256",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 7,
    "parentIndex": 1,
    "parentName": "desc",
  },
  {
    "name": "param1",
    "type": "string",
    "baseType": "string",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 8,
    "parentIndex": 8,
    "parentName": "desc extraParams",
  },
  {
    "name": "param2",
    "type": "string",
    "baseType": "string",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 9,
    "parentIndex": 8,
    "parentName": "desc extraParams",
  },
  {
    "name": "data",
    "type": "bytes",
    "baseType": "bytes",
    "components": null,
    "arrayLength": null,
    "arrayChildren": null,
    "index": 10,
    "parentIndex": null,
    "parentName": "",
  },
];


const mockFunc2 = FunctionFragment.from({
  "type": "function",
  "inputs":
    [
      {
        "name": "executor",
        "type": "address",
        "baseType": "address",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "desc",
        "type": "tuple",
        "baseType": "tuple",
        "components":
          [
            {
              "name": "srcToken",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "dstToken",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "srcReceiver",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "dstReceiver",
              "type": "address",
              "baseType": "address",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "amount",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "minReturnAmount",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "flags",
              "type": "uint256",
              "baseType": "uint256",
              "components": null,
              "arrayLength": null,
              "arrayChildren": null,
            },
            {
              "name": "extraParams",
              "type": "tuple",
              "baseType": "tuple",
              "components":
                [
                  {
                    "name": "param1",
                    "type": "string",
                    "baseType": "string",
                    "components": null,
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                  {
                    "name": "param2",
                    "type": "string",
                    "baseType": "string",
                    "components": null,
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                  {
                    "name": "param3",
                    "type": "tuple",
                    "baseType": "tuple",
                    "components": [
                      {
                        "name": "param3_1",
                        "type": "string",
                        "baseType": "string",
                        "components": null,
                        "arrayLength": null,
                        "arrayChildren": null,
                      },
                      {
                        "name": "param3_2",
                        "type": "string",
                        "baseType": "string",
                        "components": null,
                        "arrayLength": null,
                        "arrayChildren": null,
                      },
                    ],
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                  {
                    "name": "param4",
                    "type": "string",
                    "baseType": "string",
                    "components": null,
                    "arrayLength": null,
                    "arrayChildren": null,
                  },
                ],
              "arrayLength": null,
              "arrayChildren": null,
            },
          ],
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "data",
        "type": "bytes",
        "baseType": "bytes",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
    ],
  "name": "swap",
  "constant": false,
  "outputs":
    [
      {
        "name": "returnAmount",
        "type": "uint256",
        "baseType": "uint256",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
      {
        "name": "spentAmount",
        "type": "uint256",
        "baseType": "uint256",
        "components": null,
        "arrayLength": null,
        "arrayChildren": null,
      },
    ],
  "stateMutability": "payable",
  "payable": true,
  "gas": null,
}) as FunctionFragment;
